import joblib

def modelprediction(model, data):
    """
    Generates predictions using a given model and input data.

    Args:
        model: The machine learning model used for prediction.
        data: The input data to be passed to the model for prediction.

    Returns:
        The prediction(s) generated by the model for the given data.
    """
    return model.predict(data)

def load_model(model_path):
    """
    Loads a machine learning model from a specified file path.

    Args:
        model_path: The file path to the saved model.

    Returns:
        The loaded machine learning model.
    """
    return joblib.load(model_path)

